### PR TITLE
Added Javadoc to some methods

### PR DESCRIPTION
**Pull request by LauraLaureus**
I hope this is fine for you. If not, please contact me  I will do my best to help you

### CODE REVIEW

**Comment by LauraLaureus** [comment]
What does this error mean?

**Comment by johnmcclean-aol** [comment]
Travis (CI) Java support hasn't been updated in a while, so the build is failing there

**Comment by LauraLaureus** [comment]
Is it my fault? Can I do something for fixing it?

**Comment by johnmcclean-aol** [comment]
Not your fault :)
I'm not sure if it is fixable, it broke  a while ago, and I hacked around it a bit and got it working again but then it stopped working again. 
I'll create a ticket to look into again at some point.

Going to merge your PR in - thanks!

**Pull request merged**
